package uz.infosec.risk.domain;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.time.Instant;

/**
 * An application user.
 *
 * <p><b>Lombok note:</b> we use @Getter/@Setter, never @Data, on JPA entities.
 * @Data generates equals()/hashCode() over every field - including the
 * collection fields and the id. For an entity that breaks in two ways: the
 * hash code changes when the id is assigned on save (corrupting any HashSet the
 * entity is already in), and equals() triggers lazy loading of associations.
 *
 * <p><b>Column mapping:</b> Java uses camelCase, SQL uses snake_case. Hibernate's
 * default naming strategy converts between them automatically, so
 * {@code passwordHash} finds {@code password_hash} without an explicit
 * @Column(name=...). The explicit names below are documentation, not necessity.
 */
@Entity
@Table(name = "users")
@Getter
@Setter
@NoArgsConstructor
public class User {

    /**
     * GenerationType.IDENTITY = "let the database assign it"
     * (our GENERATED BY DEFAULT AS IDENTITY column). Hibernate reads the value
     * back after the INSERT.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(nullable = false, unique = true, length = 64)
    private String username;

    /** BCrypt hash. The plaintext password is never stored or logged. */
    @Column(name = "password_hash", nullable = false)
    private String passwordHash;

    @Column(name = "full_name", nullable = false)
    private String fullName;

    @Column(unique = true)
    private String email;

    /**
     * EnumType.STRING stores "ADMIN"/"USER" as text.
     * Never use the default EnumType.ORDINAL: it stores the enum's *position*,
     * so reordering or inserting a constant silently rewrites the meaning of
     * every existing row.
     */
    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 16)
    private Role role;

    /** Deactivated users cannot log in and their existing tokens are rejected. */
    @Column(nullable = false)
    private boolean active = true;

    @Column(name = "created_at", nullable = false)
    private Instant createdAt;

    @Column(name = "updated_at")
    private Instant updatedAt;

    /** JPA lifecycle callbacks: Hibernate calls these around INSERT/UPDATE. */
    @PrePersist
    void onCreate() {
        this.createdAt = Instant.now();
    }

    @PreUpdate
    void onUpdate() {
        this.updatedAt = Instant.now();
    }
}
