-- Flyway migration V1: application users.
--
-- Flyway runs every V*.sql file in filename order exactly once, and records it
-- in the flyway_schema_history table. Never edit a migration that has already
-- run on any machine - add a new one instead.
--
-- Syntax note: GENERATED BY DEFAULT AS IDENTITY and CHECK constraints are
-- understood by both H2 (PostgreSQL mode) and real PostgreSQL, so this file
-- will not need changes when we switch databases.

CREATE TABLE users
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      VARCHAR(64)  NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    full_name     VARCHAR(255) NOT NULL,
    email         VARCHAR(255),
    role          VARCHAR(16)  NOT NULL,
    active        BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMP,

    CONSTRAINT uq_users_username UNIQUE (username),
    CONSTRAINT uq_users_email UNIQUE (email),
    CONSTRAINT ck_users_role CHECK (role IN ('ADMIN', 'USER'))
);
