-- Flyway migration V2: per-module, per-action permission grants + admin seed.
--
-- Design note: this is an "access control list" table, not a role table.
-- A role (ADMIN / USER) says WHO you are; these rows say WHAT you may do.
-- ADMIN bypasses this table entirely in code - we never insert grant rows for
-- admins, because "admin can do everything" must stay true even when a new
-- module is added later.

CREATE TABLE user_module_permissions
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT      NOT NULL,
    module     VARCHAR(32) NOT NULL,
    can_create BOOLEAN     NOT NULL DEFAULT FALSE,
    can_read   BOOLEAN     NOT NULL DEFAULT TRUE,
    can_update BOOLEAN     NOT NULL DEFAULT FALSE,
    can_delete BOOLEAN     NOT NULL DEFAULT FALSE,

    CONSTRAINT fk_ump_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT uq_ump_user_module UNIQUE (user_id, module),
    CONSTRAINT ck_ump_module CHECK (module IN
        ('ASSETS', 'THREATS', 'RISKS', 'CONTROLS', 'RISK_CONTROLS', 'DICTIONARIES', 'INFO_SYSTEMS'))
);

-- Look-ups are always "all permissions for one user" (done once per request),
-- so a single index on user_id covers every query we make.
CREATE INDEX ix_ump_user ON user_module_permissions (user_id);

-- Seed administrator. Password is 'admin' - DEV ONLY, change before production.
-- The value below is a BCrypt hash (cost factor 10). BCrypt embeds its own
-- random salt in the string, which is why the hash starts with $2a$10$ and is
-- different every time it is generated - and why you cannot "look up" a
-- password by its hash.
INSERT INTO users (username, password_hash, full_name, email, role, active, created_at)
VALUES ('admin',
        '$2a$10$tpNWKUYPvEfneRA/pe98xuIDgZ9/pRPWAdK8/OGP9X/cDFjSJmdYy',
        'Administrator',
        'admin@bank.local',
        'ADMIN',
        TRUE,
        CURRENT_TIMESTAMP);
