-- Flyway migration V3: the "Техническая страница" dictionaries.
--
-- One table with a dict_type discriminator rather than four near-identical
-- tables: the shapes are the same (label + optional numeric value + order),
-- and every dropdown in the UI is then served by a single endpoint.
--
-- numeric_value is NOT decoration. For ASSET_CRITICALITY it is the asset
-- rating 1-5 that feeds the risk formula (Excel: VLOOKUP into 'Техническая
-- страница'!$A$2:$B$6). For methods and statuses it is meaningless, hence NULL.

CREATE TABLE dictionary_items
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dict_type     VARCHAR(32) NOT NULL,
    label         VARCHAR(64) NOT NULL,
    numeric_value INT,
    sort_order    INT         NOT NULL DEFAULT 0,

    CONSTRAINT uq_dict_type_label UNIQUE (dict_type, label),
    CONSTRAINT ck_dict_type CHECK (dict_type IN
        ('ASSET_CRITICALITY', 'THREAT_LEVEL', 'TREATMENT_METHOD', 'MEASURE_STATUS')),
    CONSTRAINT ck_dict_numeric CHECK (numeric_value IS NULL OR numeric_value BETWEEN 1 AND 5)
);

CREATE INDEX ix_dict_type ON dictionary_items (dict_type, sort_order);

-- Seed values copied verbatim from the workbook's Техническая страница sheet
-- (columns A/B, C/D, E, F).

INSERT INTO dictionary_items (dict_type, label, numeric_value, sort_order) VALUES
    ('ASSET_CRITICALITY', 'Очень низкая', 1, 1),
    ('ASSET_CRITICALITY', 'Низкая',       2, 2),
    ('ASSET_CRITICALITY', 'Средняя',      3, 3),
    ('ASSET_CRITICALITY', 'Высокая',      4, 4),
    ('ASSET_CRITICALITY', 'Критичная',    5, 5);

INSERT INTO dictionary_items (dict_type, label, numeric_value, sort_order) VALUES
    ('THREAT_LEVEL', 'Незначительный', 1, 1),
    ('THREAT_LEVEL', 'Низкий',         2, 2),
    ('THREAT_LEVEL', 'Средний',        3, 3),
    ('THREAT_LEVEL', 'Высокий',        4, 4),
    ('THREAT_LEVEL', 'Очень высокий',  5, 5);

INSERT INTO dictionary_items (dict_type, label, numeric_value, sort_order) VALUES
    ('TREATMENT_METHOD', 'Снижение',    NULL, 1),
    ('TREATMENT_METHOD', 'Перемещение', NULL, 2),
    ('TREATMENT_METHOD', 'Избегание',   NULL, 3),
    ('TREATMENT_METHOD', 'Принятие',    NULL, 4);

INSERT INTO dictionary_items (dict_type, label, numeric_value, sort_order) VALUES
    ('MEASURE_STATUS', 'Укладывается в срок', NULL, 1),
    ('MEASURE_STATUS', 'Задержка',            NULL, 2),
    ('MEASURE_STATUS', 'Проблема',            NULL, 3),
    ('MEASURE_STATUS', 'Выполнено',           NULL, 4);
