-- Flyway migration V4: the three core registries + the info-system inventory.
--
-- Computed columns (criticality_rating, total_score, rating, level_label) are
-- stored, not derived on read. They are recalculated by the backend on every
-- write. Storing them keeps the risk-matrix GROUP BY and dashboard queries to a
-- single indexed scan instead of recomputing formulas for every row.

-- Перечень инфосистем Банка (hidden sheet in the workbook)
CREATE TABLE info_systems
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code             VARCHAR(16)  NOT NULL,
    name             VARCHAR(255) NOT NULL,
    description      TEXT,
    hosting          TEXT,
    usage_purpose    TEXT,
    data_format      VARCHAR(32),
    confidentiality  VARCHAR(32),
    integrity        VARCHAR(8),
    availability     VARCHAR(8),
    update_frequency VARCHAR(64),
    users_info       TEXT,
    owner            VARCHAR(255),

    created_at       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by       VARCHAR(64),
    updated_at       TIMESTAMP,
    updated_by       VARCHAR(64),

    CONSTRAINT uq_info_systems_code UNIQUE (code)
);

-- Реестр ключевых ИА
CREATE TABLE assets
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code               VARCHAR(16)  NOT NULL,
    info_system_id     BIGINT,
    name               VARCHAR(255) NOT NULL,
    scope              VARCHAR(255),
    info_category      VARCHAR(255),
    criticality        VARCHAR(32)  NOT NULL,
    -- Excel column H: VLOOKUP(criticality, 'Техническая страница'!A2:B6, 2)
    criticality_rating INT          NOT NULL,
    security_class     VARCHAR(8),

    created_at         TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by         VARCHAR(64),
    updated_at         TIMESTAMP,
    updated_by         VARCHAR(64),

    CONSTRAINT uq_assets_code UNIQUE (code),
    CONSTRAINT fk_assets_info_system FOREIGN KEY (info_system_id) REFERENCES info_systems (id),
    CONSTRAINT ck_assets_rating CHECK (criticality_rating BETWEEN 1 AND 5)
);

-- Реестр угроз (DREAD)
CREATE TABLE threats
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code            VARCHAR(16) NOT NULL,
    description     TEXT        NOT NULL,
    -- The five DREAD criteria. Excel clamps each to 0..5 in helper columns L-P.
    discoverability INT         NOT NULL,
    repeatability   INT         NOT NULL,
    exploitability  INT         NOT NULL,
    affected_users  INT         NOT NULL,
    damage          INT         NOT NULL,
    -- Excel col Q: SUM(L:P)
    total_score     INT         NOT NULL,
    -- Excel col R: IF(Q<6,1,IF(Q<11,2,IF(Q<16,3,IF(Q<21,4,5))))
    rating          INT         NOT NULL,
    -- Excel col H: rating -> Незначительный/Низкий/Средний/Высокий/Очень высокий
    level_label     VARCHAR(32) NOT NULL,

    created_at      TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by      VARCHAR(64),
    updated_at      TIMESTAMP,
    updated_by      VARCHAR(64),

    CONSTRAINT uq_threats_code UNIQUE (code),
    CONSTRAINT ck_threats_discoverability CHECK (discoverability BETWEEN 0 AND 5),
    CONSTRAINT ck_threats_repeatability CHECK (repeatability BETWEEN 0 AND 5),
    CONSTRAINT ck_threats_exploitability CHECK (exploitability BETWEEN 0 AND 5),
    CONSTRAINT ck_threats_affected_users CHECK (affected_users BETWEEN 0 AND 5),
    CONSTRAINT ck_threats_damage CHECK (damage BETWEEN 0 AND 5),
    CONSTRAINT ck_threats_total CHECK (total_score BETWEEN 0 AND 25),
    CONSTRAINT ck_threats_rating CHECK (rating BETWEEN 1 AND 5)
);

-- Риск-контроль (catalog)
CREATE TABLE controls
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code             VARCHAR(16)   NOT NULL,
    name             VARCHAR(500)  NOT NULL,
    description      TEXT,
    treatment_method VARCHAR(32)   NOT NULL,
    -- Excel 'Процент снижения риска', e.g. 0.20. DECIMAL, never DOUBLE:
    -- binary floating point cannot represent 0.1 exactly, and these values are
    -- multiplied together down a chain.
    reduction_pct    DECIMAL(4, 2) NOT NULL,
    implemented      BOOLEAN       NOT NULL DEFAULT FALSE,

    created_at       TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by       VARCHAR(64),
    updated_at       TIMESTAMP,
    updated_by       VARCHAR(64),

    CONSTRAINT uq_controls_code UNIQUE (code),
    CONSTRAINT ck_controls_reduction CHECK (reduction_pct >= 0 AND reduction_pct <= 1)
);

CREATE INDEX ix_assets_info_system ON assets (info_system_id);
CREATE INDEX ix_assets_rating ON assets (criticality_rating);
CREATE INDEX ix_threats_rating ON threats (rating);
