-- Flyway migration V5: the risk register and its control links.
--
-- A risk is one (asset x threat) pair. The snapshot columns below are the
-- denormalised results of RiskCalculationService, recomputed inside the same
-- transaction as any change that can affect them. They exist so the risk matrix
-- and dashboard are plain indexed aggregates rather than per-row formula runs.

CREATE TABLE risks
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code                    VARCHAR(16)  NOT NULL,
    asset_id                BIGINT       NOT NULL,
    threat_id               BIGINT       NOT NULL,
    name                    VARCHAR(500) NOT NULL,
    indicators              TEXT,
    owner                   VARCHAR(255),
    treatment_method        VARCHAR(32),
    measure_status          VARCHAR(64),
    implementation_deadline DATE,
    comment                 TEXT,

    -- Inherent: the threat's raw DREAD rating, before any control.
    -- (The workbook has no such column; it is an addition of this platform.)
    inherent_threat_rating  INT,
    inherent_risk_level     INT,
    inherent_risk_label     VARCHAR(32),

    -- Current: after IMPLEMENTED controls only. Excel cols AW / BV / BW.
    current_score           DECIMAL(8, 4),
    current_threat_rating   INT,
    current_risk_level      INT,
    current_risk_label      VARCHAR(32),

    -- Residual: after IMPLEMENTED + PLANNED. Excel cols BG / BH / BU.
    residual_score          DECIMAL(8, 4),
    residual_threat_rating  INT,
    residual_risk_level     INT,
    residual_risk_label     VARCHAR(32),

    created_at              TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by              VARCHAR(64),
    updated_at              TIMESTAMP,
    updated_by              VARCHAR(64),

    CONSTRAINT uq_risks_code UNIQUE (code),
    -- One risk per asset x threat pair, matching how the workbook is used.
    CONSTRAINT uq_risks_asset_threat UNIQUE (asset_id, threat_id),
    CONSTRAINT fk_risks_asset FOREIGN KEY (asset_id) REFERENCES assets (id),
    CONSTRAINT fk_risks_threat FOREIGN KEY (threat_id) REFERENCES threats (id),
    CONSTRAINT ck_risks_inherent_level CHECK (inherent_risk_level IS NULL OR inherent_risk_level BETWEEN 1 AND 5),
    CONSTRAINT ck_risks_current_level CHECK (current_risk_level IS NULL OR current_risk_level BETWEEN 1 AND 5),
    CONSTRAINT ck_risks_residual_level CHECK (residual_risk_level IS NULL OR residual_risk_level BETWEEN 1 AND 5)
);

-- Replaces Excel columns R-AD (7 implemented + 5 planned, hard-coded).
-- A link row, so a risk may carry any number of controls.
CREATE TABLE risk_controls
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    risk_id      BIGINT      NOT NULL,
    control_id   BIGINT      NOT NULL,
    -- 'Да' / 'Нет' in the workbook's Риск-контроль sheet. This, not
    -- controls.implemented, is what the calculation reads.
    control_type VARCHAR(16) NOT NULL,
    apply_order  INT         NOT NULL DEFAULT 0,

    CONSTRAINT fk_rc_risk FOREIGN KEY (risk_id) REFERENCES risks (id) ON DELETE CASCADE,
    CONSTRAINT fk_rc_control FOREIGN KEY (control_id) REFERENCES controls (id),
    -- A control is attached to a risk at most once - it cannot be both
    -- implemented and planned for the same risk.
    CONSTRAINT uq_rc_risk_control UNIQUE (risk_id, control_id),
    CONSTRAINT ck_rc_type CHECK (control_type IN ('IMPLEMENTED', 'PLANNED'))
);

CREATE INDEX ix_risks_asset ON risks (asset_id);
CREATE INDEX ix_risks_threat ON risks (threat_id);
CREATE INDEX ix_risks_current_level ON risks (current_risk_level);
CREATE INDEX ix_rc_risk ON risk_controls (risk_id);
CREATE INDEX ix_rc_control ON risk_controls (control_id);
